### ISSUE TITLE
[Issue] Edit Drop

### ISSUE THREAD

**Issue by megamineservidores** [GC-spigot/AdvancedSpawners#111]
When I'm going to edit a drop, the first time goes well, next time when I click on the chest and dps on the paper, this error

[10:29:17 INFO]: PaulloHS issued server command: /as drops
[10:29:20 ERROR]: Could not pass event InventoryClickEvent to AdvancedSpawners v2.2.6
java.lang.IllegalArgumentException: Material cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61) ~[patched_1.15.2.jar:git-Paper-342]
        at gc.spawners.utils.ItemBuilder.<init>(ItemBuilder.java:52) ~[?:?]
        at gc.spawners.handlers.dropsEditor.DropsEditorGUI.editDrop(DropsEditorGUI.java:118) ~[?:?]
        at gc.spawners.handlers.dropsEditor.DropsEditSpecificClick.onClick(DropsEditSpecificClick.java:55) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor496.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-342]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2375) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1104) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1058) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:973) ~[patched_1.15.2.jar:git-Paper-342]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [e.g. 2.2.6]

**Comment by GC-spigot** [comment]
Invalid material
