### ISSUE TITLE
[Issue] Itemspawner can't be stacked probably 

### ISSUE THREAD

**Issue by ZephyalGates** [GC-spigot/AdvancedSpawners#136]
**Describe the bug**
When Itemspawner is placed together, they merged into one, but the number in the holographic display and the spawn rate remain the same.

**To Reproduce**
Having only the followings plugins installed
Advanced Spawner 2.3.0
ProtocolLib 4.5.1
Holographic Displays 2.4.3

**Screenshots / Video**
https://imgur.com/6yCLmd6

**Log**
net.minecraft.server.v1_15_R1.ReportedException: Loading entity NBT
	at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1857) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityTypes.lambda$a$1(EntityTypes.java:305) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.SystemUtils.a(SystemUtils.java:233) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:302) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityTypes.b(EntityTypes.java:346) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:327) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:130) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.TileEntityMobSpawner.tick(SourceFile:62) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.World.tickBlockEntities(World.java:798) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:570) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-380]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityItem.setItemStack(EntityItem.java:433) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityItem.a(EntityItem.java:316) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1770) ~[patched_1.15.2.jar:git-Paper-380]
	... 14 more

**Server Information (please complete the following information):**
 - Minecraft Version 1.15.2 [paper-380]
 - Advanced Spawner 2.3.0
 - ProtocolLib 4.5.1
 - Holographic Displays 2.4.3

Also I know this has been reported, but I wanna express I too have the problem that Vanilla spawner and Item spawner but not customMobs spawner will become pig spawner once placed if Advanced Spawner and WildStacker are both installed

**Comment by GC-spigot** [comment]
Which WildStacker version are you using?
Will look into this stacking issue.

**Comment by ZephyalGates** [comment]
For the main issue above I do not have WildStacker installed
For the issue of spawner turning into pig spawner I am using WildStacker 3.1.2

**Comment by GC-spigot** [comment]
> For the main issue above I do not have WildStacker installed
> For the issue of spawner turning into pig spawner I am using WildStacker 3.1.2

Ok thank you for the information - I have fixed the item spawners stacking issue, the update is going up in few minutes, am looking into wildstacker issues at the moment.

**Comment by ZephyalGates** [comment]
Thank you

**Comment by ZephyalGates** [comment]
Just tested the latest version, the holographic display problem is solved, but the problem of stacked itemspawner spawn rate is still here, there are no difference when I place 1 itemspawner or stack 1000 itemspawner.

I got this same error log:

[21:18:23] [Server thread/WARN]: Exception loading entity: 
net.minecraft.server.v1_15_R1.ReportedException: Loading entity NBT
	at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1857) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityTypes.lambda$a$1(EntityTypes.java:305) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.SystemUtils.a(SystemUtils.java:233) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:302) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityTypes.b(EntityTypes.java:346) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:327) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:130) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.TileEntityMobSpawner.tick(SourceFile:62) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.World.tickBlockEntities(World.java:798) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:570) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-380]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityItem.setItemStack(EntityItem.java:433) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.EntityItem.a(EntityItem.java:316) ~[patched_1.15.2.jar:git-Paper-380]
	at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1770) ~[patched_1.15.2.jar:git-Paper-380]

Should I open another ticket?

**Comment by GC-spigot** [comment]
Alright, will look into this. What material are the spawners dropping?

**Comment by ZephyalGates** [comment]
I have tested dirt, stone, all kinds of ores, but I do believe this happens to all material.

**Comment by ZephyalGates** [comment]
> Alright, will look into this. What material are the spawners dropping?
> […](#)
> On 2020-07-26, at 04:21 PM, ZephyalGates ***@***.***> wrote: ﻿ Just tested the latest version, the holographic display problem is solved, but the problem of stacked itemspawner spawn rate is still here, there are no difference when I place 1 itemspawner or stack 1000 itemspawner. I got this same error log: [21:18:23] [Server thread/WARN]: Exception loading entity: net.minecraft.server.v1_15_R1.ReportedException: Loading entity NBT at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1857) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.EntityTypes.lambda$a$1(EntityTypes.java:305) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.SystemUtils.a(SystemUtils.java:233) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:302) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.EntityTypes.b(EntityTypes.java:346) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:327) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:130) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.TileEntityMobSpawner.tick(SourceFile:62) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.World.tickBlockEntities(World.java:798) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:570) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-380] at java.lang.Thread.run(Unknown Source) [?:1.8.0_181] Caused by: java.lang.IllegalArgumentException: Cannot drop air at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.EntityItem.setItemStack(EntityItem.java:433) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.EntityItem.a(EntityItem.java:316) ~[patched_1.15.2.jar:git-Paper-380] at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1770) ~[patched_1.15.2.jar:git-Paper-380] Should I open another ticket? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

They drop whatever their type is, there are no problems with that, sorry I misunderstood your question.
