### ISSUE TITLE
Doesn't work on 1.16.2

### ISSUE THREAD

**Issue by 4Cris** [GC-spigot/AdvancedSpawners#149]
May you please update the plugin for 1.16.2 servers?
Thanks

**Comment by Kesims** [comment]
yeah, i would love that too.. I bought your plugin yeseterday and it doesn not work... (but in description on spigot is 1.16.x)

`[08:07:30 INFO]: [AdvancedSpawners] Enabling AdvancedSpawners v2.4.2
[08:07:30 INFO]: [AdvancedRobots] You are using invalid version of Minecraft [v1_16_R2]! Disabling...
[08:07:30 INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v2.4.2
[08:07:30 ERROR]: Error occurred while disabling AdvancedSpawners v2.4.2 (Is it up to date?)
java.lang.NullPointerException: null
        at gc.spawners.Core.onDisable(Core.java:341) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[patched_1.16.2.jar:git-Paper-145]
        at gc.spawners.nbt.backend.utils.MinecraftVersion.getVersion(MinecraftVersion.java:52) ~[?:?]
        at gc.spawners.utils.ASManager.getMaterial(ASManager.java:22) ~[?:?]
        at gc.spawners.handlers.customMobs.entityBuilders.PartProperty.<init>(PartProperty.java:59) ~[?:?]
        at gc.spawners.handlers.customMobs.entityBuilders.EntityBase.<init>(EntityBase.java:50) ~[?:?]
        at gc.spawners.handlers.customMobs.CustomEntityHandler.readAnimations(CustomEntityHandler.java:43) ~[?:?]
        at gc.spawners.handlers.customMobs.CustomEntityHandler.<init>(CustomEntityHandler.java:26) ~[?:?]
        at gc.spawners.Core.reload(Core.java:103) ~[?:?]
        at gc.spawners.Core.onEnable(Core.java:87) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-145]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[08:07:30 INFO]: [AdvancedSpawners] Loaded 11 mob configurations.
[08:07:30 INFO]: [AdvancedSpawners] Loaded 3 mob animations.
[08:07:30 ERROR]: Error occurred while enabling AdvancedSpawners v2.4.2 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:140) ~[patched_1.16.2.jar:git-Paper-145]
        at gc.spawners.handlers.customMobs.CustomEntityHandler.readAnimations(CustomEntityHandler.java:220) ~[?:?]
        at gc.spawners.handlers.customMobs.CustomEntityHandler.<init>(CustomEntityHandler.java:26) ~[?:?]
        at gc.spawners.Core.reload(Core.java:103) ~[?:?]
        at gc.spawners.Core.onEnable(Core.java:87) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-145]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]`

**Comment by GC-spigot** [comment]
Will add 1.16.2 support today

**Comment by 4Cris** [comment]
> Will add 1.16.2 support today
> […](#)
> On 2020-08-26, at 09:13 AM, Kesims ***@***.***> wrote: ﻿ yeah, i would love that too.. I bought your plugin yeseterday and it doesn not work... (but in description on spigot is 1.16.x) [08:07:30 INFO]: [AdvancedSpawners] Enabling AdvancedSpawners v2.4.2 [08:07:30 INFO]: [AdvancedRobots] You are using invalid version of Minecraft [v1_16_R2]! Disabling... [08:07:30 INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v2.4.2 [08:07:30 ERROR]: Error occurred while disabling AdvancedSpawners v2.4.2 (Is it up to date?) java.lang.NullPointerException: null at gc.spawners.Core.onDisable(Core.java:341) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[patched_1.16.2.jar:git-Paper-145] at gc.spawners.nbt.backend.utils.MinecraftVersion.getVersion(MinecraftVersion.java:52) ~[?:?] at gc.spawners.utils.ASManager.getMaterial(ASManager.java:22) ~[?:?] at gc.spawners.handlers.customMobs.entityBuilders.PartProperty.<init>(PartProperty.java:59) ~[?:?] at gc.spawners.handlers.customMobs.entityBuilders.EntityBase.<init>(EntityBase.java:50) ~[?:?] at gc.spawners.handlers.customMobs.CustomEntityHandler.readAnimations(CustomEntityHandler.java:43) ~[?:?] at gc.spawners.handlers.customMobs.CustomEntityHandler.<init>(CustomEntityHandler.java:26) ~[?:?] at gc.spawners.Core.reload(Core.java:103) ~[?:?] at gc.spawners.Core.onEnable(Core.java:87) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-145] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] [08:07:30 INFO]: [AdvancedSpawners] Loaded 11 mob configurations. [08:07:30 INFO]: [AdvancedSpawners] Loaded 3 mob animations. [08:07:30 ERROR]: Error occurred while enabling AdvancedSpawners v2.4.2 (Is it up to date?) org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:140) ~[patched_1.16.2.jar:git-Paper-145] at gc.spawners.handlers.customMobs.CustomEntityHandler.readAnimations(CustomEntityHandler.java:220) ~[?:?] at gc.spawners.handlers.customMobs.CustomEntityHandler.<init>(CustomEntityHandler.java:26) ~[?:?] at gc.spawners.Core.reload(Core.java:103) ~[?:?] at gc.spawners.Core.onEnable(Core.java:87) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-145] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Still waiting

**Comment by Kesims** [comment]
> > Will add 1.16.2 support today
> > […](#)
> > On 2020-08-26, at 09:13 AM, Kesims _**@**_.***> wrote: ﻿ yeah, i would love that too.. I bought your plugin yeseterday and it doesn not work... (but in description on spigot is 1.16.x) [08:07:30 INFO]: [AdvancedSpawners] Enabling AdvancedSpawners v2.4.2 [08:07:30 INFO]: [AdvancedRobots] You are using invalid version of Minecraft [v1_16_R2]! Disabling... [08:07:30 INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v2.4.2 [08:07:30 ERROR]: Error occurred while disabling AdvancedSpawners v2.4.2 (Is it up to date?) java.lang.NullPointerException: null at gc.spawners.Core.onDisable(Core.java:341) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[patched_1.16.2.jar:git-Paper-145] at gc.spawners.nbt.backend.utils.MinecraftVersion.getVersion(MinecraftVersion.java:52) ~[?:?] at gc.spawners.utils.ASManager.getMaterial(ASManager.java:22) ~[?:?] at gc.spawners.handlers.customMobs.entityBuilders.PartProperty.(PartProperty.java:59) ~[?:?] at gc.spawners.handlers.customMobs.entityBuilders.EntityBase.(EntityBase.java:50) ~[?:?] at gc.spawners.handlers.customMobs.CustomEntityHandler.readAnimations(CustomEntityHandler.java:43) ~[?:?] at gc.spawners.handlers.customMobs.CustomEntityHandler.(CustomEntityHandler.java:26) ~[?:?] at gc.spawners.Core.reload(Core.java:103) ~[?:?] at gc.spawners.Core.onEnable(Core.java:87) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-145] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] [08:07:30 INFO]: [AdvancedSpawners] Loaded 11 mob configurations. [08:07:30 INFO]: [AdvancedSpawners] Loaded 3 mob animations. [08:07:30 ERROR]: Error occurred while enabling AdvancedSpawners v2.4.2 (Is it up to date?) org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:140) ~[patched_1.16.2.jar:git-Paper-145] at gc.spawners.handlers.customMobs.CustomEntityHandler.readAnimations(CustomEntityHandler.java:220) ~[?:?] at gc.spawners.handlers.customMobs.CustomEntityHandler.(CustomEntityHandler.java:26) ~[?:?] at gc.spawners.Core.reload(Core.java:103) ~[?:?] at gc.spawners.Core.onEnable(Core.java:87) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-145] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-145] at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-145] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Still waiting

1.16.2 support was added yesterday. Download it from spigot

**Comment by 4Cris** [comment]
[23:03:46] [Server thread/ERROR]: Error occurred while enabling AdvancedSpawners v2.4.5 (Is it up to date?)
java.lang.NullPointerException: null
	at gc.spawners.utils.DataHandler.getKeys(DataHandler.java:94) ~[?:?]
	at gc.spawners.handlers.shopHandler.ShopInventoryHandler.load(ShopInventoryHandler.java:29) ~[?:?]
	at gc.spawners.Core.reload(Core.java:119) ~[?:?]
	at gc.spawners.Core.onEnable(Core.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-149]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-149]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-149]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-149]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-149]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[23:03:46] [Server thread/INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v2.4.5
[23:03:46] [Server thread/ERROR]: Error occurred while disabling AdvancedSpawners v2.4.5 (Is it up to date?)
java.lang.NullPointerException: null
	at gc.spawners.Core.onDisable(Core.java:342) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-149]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-149]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-149]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-149]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-149]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-149]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by GC-spigot** [comment]
Reset your spawner shop file
