### ISSUE TITLE
I have the following error in the console

### ISSUE THREAD

**Issue by Endphoenix** [GC-spigot/AdvancedSpawners#153]
**Describe the bug**
In the Cosnole I have this long complicated error:

[17:11:55] [Server thread/INFO]: [AdvancedSpawners] Enabling AdvancedSpawners v2.4.7
[17:11:55] [Server thread/INFO]: [AdvancedSpawners] Loaded 11 mob configurations.
[17:11:55] [Server thread/INFO]: [AdvancedSpawners] Loaded 3 mob animations.
[17:11:55] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 132, column 7:
          chance: 100
          ^
expected <block end>, but found '<scalar>'
 in 'string', line 134, column 22:
          name: 'Turtlel's Shell'
                         ^

[17:11:55] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
[17:11:55] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[17:11:55] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[17:11:55] [Server thread/WARN]: 	at gc.spawners.handlers.dropsHandler.DropsHandler.<init>(DropsHandler.java:33)
[17:11:55] [Server thread/WARN]: 	at gc.spawners.Core.reload(Core.java:106)
[17:11:55] [Server thread/WARN]: 	at gc.spawners.Core.onEnable(Core.java:87)
[17:11:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:11:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[17:11:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[17:11:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[17:11:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[17:11:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[17:11:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[17:11:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776)
[17:11:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:11:55] [Server thread/WARN]: Caused by: while parsing a block mapping
 in 'string', line 132, column 7:
          chance: 100
          ^
expected <block end>, but found '<scalar>'
 in 'string', line 134, column 22:
          name: 'Turtlel's Shell'
                         ^

[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
[17:11:55] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
[17:11:55] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
[17:11:55] [Server thread/WARN]: 	... 14 more
[17:11:55] [Server thread/ERROR]: Error occurred while enabling AdvancedSpawners v2.4.7 (Is it up to date?)
java.lang.NullPointerException: null
	at gc.spawners.utils.DataHandler.getKeys(DataHandler.java:94) ~[?:?]
	at gc.spawners.handlers.shopHandler.ShopInventoryHandler.load(ShopInventoryHandler.java:29) ~[?:?]
	at gc.spawners.Core.reload(Core.java:119) ~[?:?]
	at gc.spawners.Core.onEnable(Core.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [craftbukkit.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [craftbukkit.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [craftbukkit.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [craftbukkit.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [craftbukkit.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [craftbukkit.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [craftbukkit.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**To Reproduce**
A way to reproduce the video
-

**Screenshots / Video**
-

**Server Information (please complete the following information):**
 - Minecraft Version: Spigot 1.14.4
- Plugin Version: AdvancedSpawners-2.4.8

**Comment by myiume** [comment]
This looks to me like the configuration parser is having issues reading your configuration. Please make sure you properly closed quotations.
