### ISSUE TITLE
[Issue] error that spamms console on elapsedspigot 1.8 when you place a spawner

### ISSUE THREAD

**Issue by jjtd123** [GC-spigot/AdvancedSpawners#193]
[20:26:19 WARN]: java.lang.Throwable
[20:26:19 WARN]:        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[20:26:19 WARN]:        at org.spigotmc.ActivationRange.checkIfActive(ActivationRange.java:282)
[20:26:19 WARN]:        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:2022)
[20:26:19 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:256)
[20:26:19 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:422)
[20:26:19 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236)
[20:26:19 WARN]:        at gc.spawners.handlers.customSpawners.data.SpawnerData.spinDisplay(SpawnerData.java:187)
[20:26:19 WARN]:        at java.util.HashMap$Values.forEach(Unknown Source)
[20:26:19 WARN]:        at gc.spawners.handlers.customSpawners.SpawnersHandler$4.run(SpawnersHandler.java:66)
[20:26:19 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[20:26:19 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:26:19 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:26:19 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:26:19 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:26:19 ERROR]: stopTiming called async for checkIfActive

**Comment by GC-spigot** [comment]
Fixed
