### ISSUE TITLE
[Issue] plugin doesnt load

### ISSUE THREAD

**Issue by Hexiss** [GC-spigot/AdvancedSpawners#209]
Hi, When i try to modify the   language: 'en' to   language: 'fr'

>.... [12:34:24 INFO]: [AdvancedSpawners] Enabling AdvancedSpawners v3.1.2
>.... [12:34:24 INFO]: [AdvancedSpawners] Loaded 36,570 custom heads
>.... [12:34:24 INFO]: [AdvancedSpawners] Loaded 10 mob configurations.
>.... [12:34:24 INFO]: [AdvancedSpawners] Failed to load drops for mob Bear: unknown entity type
>.... [12:34:24 ERROR]: Error occurred while enabling AdvancedSpawners v3.1.2 (Is it up to date?)
java.lang.NullPointerException: null
at gcspawners.CustomMobNames.<init>(CustomMobNames.java:17) ~[?:?]
at gcspawners.Core.loadBasics(Core.java:385) ~[?:?]
at gcspawners.Core.onEnable(Core.java:105) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:242) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.5.jar:git-Tuinity-"aea6b83"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
>.... [12:34:24 INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v3.1.2

Im using paper 1.16.5 last version

**Comment by GC-spigot** [comment]
There's no `fr` language file. You need to create one in locale folder by copy pasting one of the default lang files and then use that file
