### ISSUE TITLE
[Issue]Plugin not enabling on startup: Cannot find main class `gc.spawners.Core'

### ISSUE THREAD

**Issue by MilleniumModsSources** [GC-spigot/AdvancedSpawners#235]
**Describe the bug**
When trying to start the server, the plugin (Downloaded from AdvancedPlugins site, not sure if this issue is also there when downloading from spigot) simply does not loads, it gives this error:

Could not load 'plugins/AdvancedSpawners-3.2.2 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `gc.spawners.Core'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:84) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:392) ~[patched_1.16.5.jar:git-Purpur-1118]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:264) ~[patched_1.16.5.jar:git-Purpur-1118]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1071) ~[patched_1.16.5.jar:git-Purpur-1118]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1118]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.ClassNotFoundException: gc.spawners.Core
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1118]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1118]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_282]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Purpur-1118]
        ... 8 more

**To Reproduce**
Install the plugin and start the server.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
- Minecraft Version [Purpur 1.16.5 build 1118]
- Plugin Version [3.2.2]
- I don't have other plugins installed on the server currently.

**Comment by GC-spigot** [comment]
Fixed
