### ISSUE TITLE
People don't die

### ISSUE THREAD

**Issue by jarek11223349** [GC-spigot/AdvancedSpawners#240]
When people fall out of the world or die otherwise, their health regenerates and an error pops up on the console.

[22:40:26] [Server thread/ERROR]: Could not pass event EntityDamageEvent to AdvancedSpawners v3.2.3
java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.remove(CraftPlayer.java:2254) ~[patched_1.16.5.jar:git-Paper-590]
	at gcspawners.EntityDamageHandler.parseDamage(EntityDamageHandler.java:121) ~[?:?]
	at gcspawners.EntityDamageHandler.onNaturalDamage(EntityDamageHandler.java:161) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor709.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-590]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:250) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1070) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1052) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:913) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1102) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1932) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:941) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1260) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:858) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:972) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.Entity.entityBaseTick(Entity.java:541) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:360) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:498) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:253) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:648) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:323) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:158) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1501) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-590]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by ghost** [comment]
Reported in ticket on several occasions, vouched by Cobs.

**Comment by GC-spigot** [comment]
Will be fixed in 10 minutes

**Comment by jarek11223349** [comment]
The update did nothing, still the same problem.
