### ISSUE TITLE
[Issue] Exception on loading

### ISSUE THREAD

**Issue by SOekd** [GC-spigot/AdvancedSpawners#258]
**Describe the bug**
The plugin throws an exception on loading (PaperSpigot1.8.8)

**To Reproduce**
Start the server on 1.8.8

**Exception**
[18:06:18 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_8_R3.block.data.CraftBlockData
[18:06:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[18:06:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[18:06:18 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[18:06:18 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[18:06:18 WARN]:        at java.lang.Class.forName0(Native Method)
[18:06:18 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:06:18 WARN]:        at gcspawners.ClassWrapper.<init>(ClassWrapper.java:57)
[18:06:18 WARN]:        at gcspawners.ClassWrapper.<clinit>(ClassWrapper.java:11)
[18:06:18 WARN]:        at gcspawners.ReflectionMethod.<clinit>(ReflectionMethod.java:13)
[18:06:18 WARN]:        at gcspawners.NBTCompound.setString(NBTCompound.java:40)
[18:06:18 WARN]:        at gcspawners.NBTapi.addNBTTag(NBTapi.java:19)
[18:06:18 WARN]:        at gcspawners.ShopInventoryHandler.load(ShopInventoryHandler.java:67)
[18:06:18 WARN]:        at gcspawners.Core.reload(Core.java:314)
[18:06:18 WARN]:        at gcspawners.Core.onEnable(Core.java:105)
[18:06:18 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[18:06:18 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[18:06:18 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[18:06:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[18:06:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[18:06:18 WARN]:        at java.lang.Thread.run(Thread.java:748)
[18:06:18 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.EnumHand
[18:06:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[18:06:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[18:06:18 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[18:06:18 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[18:06:18 WARN]:        at java.lang.Class.forName0(Native Method)
[18:06:18 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:06:18 WARN]:        at gcspawners.ClassWrapper.<init>(ClassWrapper.java:57)
[18:06:18 WARN]:        at gcspawners.ClassWrapper.<clinit>(ClassWrapper.java:43)
[18:06:18 WARN]:        at gcspawners.ReflectionMethod.<clinit>(ReflectionMethod.java:13)
[18:06:18 WARN]:        at gcspawners.NBTCompound.setString(NBTCompound.java:40)
[18:06:18 WARN]:        at gcspawners.NBTapi.addNBTTag(NBTapi.java:19)
[18:06:18 WARN]:        at gcspawners.ShopInventoryHandler.load(ShopInventoryHandler.java:67)
[18:06:18 WARN]:        at gcspawners.Core.reload(Core.java:314)
[18:06:18 WARN]:        at gcspawners.Core.onEnable(Core.java:105)
[18:06:18 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[18:06:18 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[18:06:18 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[18:06:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[18:06:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[18:06:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[18:06:18 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Server Information:**
 - Minecraft Version: PaperSpigot 1.8.8
 - Plugin Version: 3.2.7

**Comment by GC-spigot** [comment]
Fixed next update
