### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by BrawlingJoker16** [GC-spigot/AdvancedSpawners#272]
**Describe the bug**
My console send me this when i install plugin, its the first time that i put in my server. how do i fix it?. The plugin doesnet works.

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/86267341/127573216-3364d674-ba14-4009-9e18-1c17b499ccae.png)

**Server Information (please complete the following information):**
 - Minecraft Version: Spigot 1.17.1
- Plugin Version: 3.3.2

**Comment by GC-spigot** [comment]
Copy paste the error not a screenshot, this doesn't have full information.

**Comment by BrawlingJoker16** [comment]
[12:02:43] [Server thread/ERROR]: Could not load 'plugins/AdvancedSpawners-3.3.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `gc.spawners.Core'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:69) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:400) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: gc.spawners.Core
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
	... 8 more
