### ISSUE TITLE
[Issue] Error after the plugin update. 

### ISSUE THREAD

**Issue by WizkhalifaX** [GC-spigot/AdvancedSpawners#280]
**Describe the bug**
The old version, has suddenly has a bug like after destroying the spawner, the head of the custom mobs was still there and spinning around and players can't even break it, and the hologram was still there, the only way to remove is to kill the server, anyways Ive been waiting for almost a weeks and there was an update, after I updated it stills won't work please help need to be fix this ASAP.... 

**To Reproduce**
NONE, atm I have shit pc... 

**Screenshots / Video**
Logs is Good Already....

**Server Information play.knightrealms.org, 1.16.5, Premium/Crack network server:**
 - Minecraft Version [PaperSpigot 1.16.5 BUILD 764]
- Plugin Version [3.3.4]

**Error Log**;
```[00:45:18] [Server thread/ERROR]: Could not load 'plugins/AdvancedSpawners-3.3.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `gc.spawners.Core'
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:84) ~[patched_1.16.5.jar:git-Paper-783]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-783]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-783]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-783]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-783]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-783]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-783]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]
    at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: gc.spawners.Core
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-783]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-783]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:466) ~[?:?]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-783]
    ... 8 more```

**Comment by GC-spigot** [comment]
Fixed
