### ISSUE TITLE
Crash 1.8 versions

### ISSUE THREAD

**Issue by SoildOfficial** [GC-spigot/AdvancedSpawners#285]
[15:33:35] [Server thread/INFO]: [AdvancedSpawners] Enabling AdvancedSpawners v3.3.2
[15:33:36] [Server thread/INFO]: [AdvancedSpawners] Loaded 36,570 custom heads
[15:33:36] [Server thread/INFO]: [AdvancedSpawners] Loaded 10 mob configurations.
[15:33:36] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:33:36] [Server thread/INFO]: Done (2.664s)! For help, type "help" or "?"
[15:33:36] [Server thread/INFO]: Timings Reset
[15:33:36] [Server thread/INFO]: [AdvancedSpawners] Loaded 0 spawners, failed to load: 0
[15:33:56] [User Authenticator #1/INFO]: UUID of player CGCNight is 37b85e8a-03b3-4ae3-b30e-dcd6d88be35c
[15:33:56] [Server thread/INFO]: CGCNight[/141.136.224.185:6636] logged in with entity id 268 at ([world]4.951284577634944, 98.0, 293.4971537218863)
[15:33:59] [Server thread/INFO]: CGCNight issued server command: /as
[15:34:12] [Server thread/INFO]: CGCNight issued server command: /as debug
[15:34:40] [Server thread/INFO]: CGCNight issued server command: /as
[15:34:42] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:34:54] [Server thread/WARN]: [AdvancedSpawners] Failed to remove a custom mob.
[15:34:54] [Server thread/WARN]: java.lang.NullPointerException
[15:34:54] [Server thread/WARN]: 	at gcspawners.CustomEntityInstance.kill(CustomEntityInstance.java:110)
[15:34:54] [Server thread/WARN]: 	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:119)
[15:34:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[15:34:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[15:34:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[15:34:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:34:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:34:54] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:34:54] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:34:54] [Server thread/WARN]: [AdvancedSpawners] Task #8 for AdvancedSpawners v3.3.2 generated an exception
java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(Unknown Source) ~[?:1.8.0_282]
	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_282]
[15:35:08] [Async Chat Thread - #0/INFO]: <CGCNight> Snake[m
[15:35:10] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:35:16] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:35:22] [Server thread/WARN]: [AdvancedSpawners] Failed to remove a custom mob.
[15:35:22] [Server thread/WARN]: java.lang.NullPointerException
[15:35:22] [Server thread/WARN]: 	at gcspawners.CustomEntityInstance.kill(CustomEntityInstance.java:110)
[15:35:22] [Server thread/WARN]: 	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:119)
[15:35:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[15:35:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[15:35:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[15:35:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:35:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:35:22] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:35:22] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:35:22] [Server thread/WARN]: [AdvancedSpawners] Task #8 for AdvancedSpawners v3.3.2 generated an exception
java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(Unknown Source) ~[?:1.8.0_282]
	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_282]
[15:35:53] [Server thread/WARN]: [AdvancedSpawners] Failed to remove a custom mob.
[15:35:53] [Server thread/WARN]: java.lang.NullPointerException
[15:35:53] [Server thread/WARN]: 	at gcspawners.CustomEntityInstance.kill(CustomEntityInstance.java:110)
[15:35:53] [Server thread/WARN]: 	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:119)
[15:35:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[15:35:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[15:35:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[15:35:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:35:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:35:53] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:35:53] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:35:53] [Server thread/WARN]: [AdvancedSpawners] Task #8 for AdvancedSpawners v3.3.2 generated an exception
java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(Unknown Source) ~[?:1.8.0_282]
	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_282]
[15:36:02] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:36:08] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:36:31] [Server thread/WARN]: [AdvancedSpawners] Failed to remove a custom mob.
[15:36:31] [Server thread/WARN]: java.lang.NullPointerException
[15:36:31] [Server thread/WARN]: 	at gcspawners.CustomEntityInstance.kill(CustomEntityInstance.java:110)
[15:36:31] [Server thread/WARN]: 	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:119)
[15:36:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[15:36:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[15:36:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[15:36:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:36:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:36:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:36:31] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:36:31] [Server thread/WARN]: [AdvancedSpawners] Task #8 for AdvancedSpawners v3.3.2 generated an exception
java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(Unknown Source) ~[?:1.8.0_282]
	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_282]
[15:36:39] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:36:49] [Server thread/WARN]: [AdvancedSpawners] Failed to remove a custom mob.
[15:36:49] [Server thread/WARN]: java.lang.NullPointerException
[15:36:49] [Server thread/WARN]: 	at gcspawners.CustomEntityInstance.kill(CustomEntityInstance.java:110)
[15:36:49] [Server thread/WARN]: 	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:119)
[15:36:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[15:36:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[15:36:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[15:36:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:36:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:36:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:36:49] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:36:49] [Server thread/WARN]: [AdvancedSpawners] Task #8 for AdvancedSpawners v3.3.2 generated an exception
java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(Unknown Source) ~[?:1.8.0_282]
	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_282]
[15:36:53] [Server thread/INFO]: CGCNight issued server command: /as
[15:36:55] [Server thread/INFO]: CGCNight issued server command: /as reload
[15:36:55] [Server thread/INFO]: [AdvancedSpawners] Loaded 11 mob configurations.
[15:37:03] [Server thread/INFO]: CGCNight issued server command: /as clearDisplays
[15:37:08] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:37:20] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:37:27] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:37:36] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:37:52] [Server thread/WARN]: [AdvancedSpawners] Failed to remove a custom mob.
[15:37:52] [Server thread/WARN]: java.lang.NullPointerException
[15:37:52] [Server thread/WARN]: 	at gcspawners.CustomEntityInstance.kill(CustomEntityInstance.java:110)
[15:37:52] [Server thread/WARN]: 	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:119)
[15:37:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[15:37:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[15:37:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[15:37:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:37:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:37:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:37:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:37:52] [Server thread/WARN]: [AdvancedSpawners] Task #51 for AdvancedSpawners v3.3.2 generated an exception
java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(Unknown Source) ~[?:1.8.0_282]
	at gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_282]
[15:37:54] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:37:58] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:38:03] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:38:09] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:38:13] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:38:26] [Server thread/INFO]: CGCNight issued server command: /as editor
[15:38:40] [Server thread/INFO]: CGCNight lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
[15:38:40] [Server thread/INFO]: CGCNight left the game.
[17:20:46] [User Authenticator #2/INFO]: UUID of player SoildOfficial is 764ef78b-7427-4ad3-a4b7-d4d2e48bc50d
[17:20:46] [Server thread/INFO]: SoildOfficial[/178.223.234.200:51459] logged in with entity id 598 at ([world]-226.1680624824188, 75.0, 71.06371306212782)
[17:21:01] [Server thread/INFO]: SoildOfficial issued server command: /as editor
[17:21:40] [User Authenticator #3/INFO]: UUID of player CGCNight is 37b85e8a-03b3-4ae3-b30e-dcd6d88be35c
[17:21:40] [Server thread/INFO]: CGCNight[/141.136.224.185:1134] logged in with entity id 2709 at ([world]3.9224671447837958, 98.0, 288.6978404597635)
[17:21:49] [Server thread/INFO]: CGCNight issued server command: /as editor
[17:21:50] [Server thread/INFO]: SoildOfficial issued server command: /as editor
[17:21:56] [Server thread/INFO]: SoildOfficial issued server command: /tp CGCNight
[17:21:56] [Server thread/INFO]: [SoildOfficial: Teleported SoildOfficial to CGCNight]
[17:21:57] [Server thread/INFO]: CGCNight issued server command: /as editor
[17:21:59] [Server thread/INFO]: CGCNight lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
[17:21:59] [Server thread/INFO]: CGCNight left the game.
[17:22:04] [Server thread/INFO]: SoildOfficial issued server command: /tp CGCNight
[17:22:04] [Server thread/INFO]: [SoildOfficial: The entity UUID provided is in an invalid format]
[17:22:06] [Server thread/INFO]: SoildOfficial issued server command: /as editor
[17:22:12] [Server thread/INFO]: SoildOfficial issued server command: /as editor
[17:22:16] [User Authenticator #4/INFO]: UUID of player CGCNight is 37b85e8a-03b3-4ae3-b30e-dcd6d88be35c
[17:22:16] [Server thread/INFO]: CGCNight[/141.136.224.185:1184] logged in with entity id 3467 at ([world]4.576531975341725, 98.0, 289.4883455759691)
[17:22:25] [Server thread/INFO]: SoildOfficial issued server command: /as editor
[17:22:45] [Server thread/INFO]: SoildOfficial issued server command: /as editor
[17:22:47] [Server thread/INFO]: CGCNight issued server command: /as clearDisplays
[17:22:50] [Server thread/INFO]: CGCNight issued server command: /as editor
[17:22:59] [Server thread/INFO]: CGCNight issued server command: /as editor
[17:23:05] [Server thread/INFO]: SoildOfficial issued server command: /as editor
[17:23:08] [Server thread/INFO]: SoildOfficial issued server command: /as editor
[17:23:13] [Server thread/INFO]: CGCNight issued server command: /as editor
[17:23:22] [Server thread/INFO]: CGCNight lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
[17:23:22] [Server thread/INFO]: CGCNight left the game.
[17:23:32] [Server thread/INFO]: SoildOfficial lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer
[17:23:32] [Server thread/INFO]: SoildOfficial left the game.
[17:23:46] [User Authenticator #5/INFO]: UUID of player CGCNight is 37b85e8a-03b3-4ae3-b30e-dcd6d88be35c
[17:23:46] [Server thread/INFO]: CGCNight[/141.136.224.185:19160] logged in with entity id 3853 at ([world]6.262841115149182, 98.0, 289.11296023295205)
[17:23:55] [Server thread/INFO]: CGCNight issued server command: /as clearDisplays
[17:31:38] [Server thread/INFO]: Stopping the server
[17:31:38] [Server thread/INFO]: Stopping server
[17:31:38] [Server thread/INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v3.3.2
[17:31:38] [Server thread/INFO]: Saving players
[17:31:38] [Server thread/INFO]: CGCNight lost connection: Server closed
[17:31:38] [Server thread/INFO]: CGCNight left the game.
[17:31:38] [Server thread/INFO]: Saving worlds
[17:31:38] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[17:31:39] [Server thread/INFO]: Saving chunks for level 'world_nether'/Nether
[17:31:39] [Server thread/INFO]: Saving chunks for level 'world_the_end'/The End

**Comment by GC-spigot** [comment]
Doesn't seem like a crash, rather just the server stopping by itself. Crash would mean there's a crash log. 

This error however will be fixed for next update.
