### ISSUE TITLE
Mcmmo Required Issue

### ISSUE THREAD

**Issue by ImYenil** [GC-spigot/AdvancedSpawners#310]
**Describe the bug**
Mcmmo required issue
**To Reproduce**
A way to reproduce the video

**Screenshots / Video**
[03:26:24] [Server thread/INFO]: [AdvancedSpawners] Loaded 10 mob configurations.
[03:26:24] [Server thread/ERROR]: Error occurred while enabling AdvancedSpawners v3.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/mcMMO
	at gcspawners.Core.reload(Core.java:329) ~[?:?]
	at gcspawners.Core.onEnable(Core.java:111) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:520) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:434) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.mcMMO
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3272-Spigot-3892929-747a73e]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 12 more

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8] Spigot 1.17.1
- Plugin Version [e.g. 6.7.8] 3.5.0

**Comment by GC-spigot** [comment]
Fixed

**Comment by ImYenil** [comment]
> Fixed

im testing new version. still issue.
