### ISSUE TITLE
PLUGIN ERROR (NOT WORKING ) [FIXED]

### ISSUE THREAD

**Issue by el211** [GC-spigot/AdvancedSpawners#312]
[18:56:21 INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v3.5.1
[18:56:21 ERROR]: Error occurred while disabling AdvancedSpawners v3.5.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "gcspawners.AdvancedSpawnerHandler.save(boolean)" because "gcspawners.Core.spawnersHandler" is null
        at gcspawners.Core.onDisable(Core.java:494) ~[AdvancedSpawners-3.5.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:535) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:307) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-311]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by el211** [comment]
[latest (2).log](https://github.com/GC-spigot/AdvancedSpawners/files/7491371/latest.2.log)

**Comment by el211** [comment]
that on is fixed 
thanks

**Comment by dinobossytnew** [comment]
https://www.spigotmc.org/resources/1-8-1-17-%E2%9C%85-advancedspawners-%E2%9C%85-11x-custom-mobs-%E2%AD%95-create-custom-mobs-in-game-%E2%9A%A1-25-sale-%E2%9A%A1.75458/updates Update the plugin. ....

**Comment by dinobossytnew** [comment]
not error.
