### ISSUE TITLE
[Bugs!]

### ISSUE THREAD

**Issue by xSmAShz1** [GC-spigot/AdvancedSpawners#314]
**Describe the bug**
I got some bugs 

**Screenshots / Video**
first bug : https://gifyu.com/image/S2MSw
second bug: https://ibb.co/zZZmW2Q
second bug photo 2: https://ibb.co/xqppVq3
bug three: NoImage but, If you have a parrot at you, any times you got dmg or you jump there is random mobs spawning inside you
bug four: Mobs are sometimes invisble, custom mobs and normal mobs, so i hit the zombie sometimes he go invisable or flying endermans or other mobs

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.17.1]
- Plugin Version [e.g. 3.5.4]

First bug:
If a slime is on a magma block my Console spamming extremly
Console spam:

[23:18:57 ERROR]: Could not pass event AdvancedEntityDeathEvent to AdvancedSpawners v3.5.4
java.lang.IllegalStateException: Unhandled damage of EntitySlime['Slime'/53372, uuid='0162d39d-e140-44d8-9e36-428f76da6aa2', l='ServerLevel[world]', x=11372.46, y=64.00, z=56503.94, cpos=[710, 3531], tl=0, v=true, rR=null] by CraftBlock{pos=BlockPosition{x=11372, y=63, z=56503},type=MAGMA_BLOCK,data=Block{minecraft:magma_block},fluid=net.minecraft.world.level.material.FluidTypeEmpty@799ed4e8} from generic
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1021) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148) ~[patched_1.17.1.jar:git-Paper-351]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:363) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:348) ~[patched_1.17.1.jar:git-Paper-351]
        at gcspawners.DeathDropsEvent.createDrops(DeathDropsEvent.java:119) ~[AdvancedSpawners-3.5.4 (1).jar:?]
        at gcspawners.DeathDropsEvent.onDeath(DeathDropsEvent.java:43) ~[AdvancedSpawners-3.5.4 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor488.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-351]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-351]
        at gcspawners.EntityDamageHandler.parseDamage(EntityDamageHandler.java:113) ~[AdvancedSpawners-3.5.4 (1).jar:?]
        at gcspawners.EntityDamageHandler.onNaturalDamage(EntityDamageHandler.java:166) ~[AdvancedSpawners-3.5.4 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor485.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-351]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1025) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-351]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148) ~[patched_1.17.1.jar:git-Paper-351]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
        at net.minecraft.world.level.block.MagmaBlock.stepOn(MagmaBlock.java:34) ~[app:?]
        at net.minecraft.world.entity.Entity.move(Entity.java:1012) ~[patched_1.17.1.jar:git-Paper-351]
        at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2790) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2745) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3207) ~[app:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:625) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2893) ~[app:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:393) ~[app:?]
        at net.minecraft.world.entity.monster.Slime.tick(Slime.java:151) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1120) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:988) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-351]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1624) ~[patched_1.17.1.jar:git-Paper-351]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-351]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-351]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by dinobossytnew** [comment]
ty report https://www.spigotmc.org/resources/1-8-1-17-%E2%9C%85-advancedspawners-%E2%9C%85-11x-custom-mobs-%E2%AD%95-create-custom-mobs-in-game-%E2%9A%A1-25-sale-%E2%9A%A1.75458/updates 

TY GC

**Comment by GC-spigot** [comment]
Update
