### ISSUE TITLE
console spammming error ( server log is attached to that message)

### ISSUE THREAD

**Issue by el211** [GC-spigot/AdvancedSpawners#315]
7:26:56 ERROR]: Could not pass event AdvancedEntityDeathEvent to AdvancedSpawners v3.5.4
java.lang.IllegalStateException: Unhandled damage of EntitySlime['Slime'/3301, uuid='d39c3e1a-776b-4ff9-9cc7-4cf046ee62a4', l='ServerLevel[arene]', x=-291.20, y=47.42, z=-556.26, cpos=[-19, -35], tl=0, v=true, rR=null] by CraftBlock{pos=BlockPosition{x=-292, y=47, z=-556},type=CACTUS,data=Block{minecraft:cactus}[age=0],fluid=net.minecraft.world.level.material.FluidTypeEmpty@36480b2d} from generic
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1021) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:363) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:348) ~[patched_1.17.1.jar:git-Paper-377]
        at gcspawners.DeathDropsEvent.createDrops(DeathDropsEvent.java:119) ~[AdvancedSpawners-3.5.4.jar:?]
        at gcspawners.DeathDropsEvent.onDeath(DeathDropsEvent.java:43) ~[AdvancedSpawners-3.5.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor542.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-377]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-377]
        at gcspawners.EntityDamageHandler.parseDamage(EntityDamageHandler.java:113) ~[AdvancedSpawners-3.5.4.jar:?]
        at gcspawners.EntityDamageHandler.onNaturalDamage(EntityDamageHandler.java:166) ~[AdvancedSpawners-3.5.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor539.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-377]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1025) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1
[latest (6).log](https://github.com/GC-spigot/AdvancedSpawners/files/7532917/latest.6.log)
.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
        at net.minecraft.world.level.block.CactusBlock.entityInside(CactusBlock.java:122) ~[app:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:925) ~[app:?]
        at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1419) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:1128) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.Entity.move(Entity.java:1059) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2790) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2745) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3207) ~[app:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:625) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2893) ~[app:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:393) ~[app:?]
        at net.minecraft.world.entity.monster.Slime.tick(Slime.java:151) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1120) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:988) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1625) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1481) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-377]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[17:26:57 ERROR]: Could not pass event AdvancedEntityDeathEvent to AdvancedSpawners v3.5.4
java.lang.IllegalStateException: Unhandled damage of EntitySlime['Slime'/3335, uuid='30ee14b6-7ada-49ff-801e-9ff630703e4e', l='ServerLevel[arene]', x=-282.49, y=47.00, z=-567.78, cpos=[-18, -36], tl=0, v=true, rR=null] by CraftBlock{pos=BlockPosition{x=-282, y=47, z=-569},type=CACTUS,data=Block{minecraft:cactus}[age=0],fluid=net.minecraft.world.level.material.FluidTypeEmpty@36480b2d} from generic
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1021) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:363) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:348) ~[patched_1.17.1.jar:git-Paper-377]
        at gcspawners.DeathDropsEvent.createDrops(DeathDropsEvent.java:119) ~[AdvancedSpawners-3.5.4.jar:?]
        at gcspawners.DeathDropsEvent.onDeath(DeathDropsEvent.java:43) ~[AdvancedSpawners-3.5.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor542.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-377]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-377]
        at gcspawners.EntityDamageHandler.parseDamage(EntityDamageHandler.java:113) ~[AdvancedSpawners-3.5.4.jar:?]
        at gcspawners.EntityDamageHandler.onNaturalDamage(EntityDamageHandler.java:166) ~[AdvancedSpawners-3.5.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor539.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-377]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1025) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-377]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
        at net.minecraft.world.level.block.CactusBlock.entityInside(CactusBlock.java:122) ~[app:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:925) ~[app:?]
        at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1419) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:1128) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.Entity.move(Entity.java:1059) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:2790) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2745) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3207) ~[app:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:625) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2893) ~[app:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:393) ~[app:?]
        at net.minecraft.world.entity.monster.Slime.tick(Slime.java:151) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1120) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:988) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1625) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1481) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-377]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by dinobossytnew** [comment]
Updates.

https://www.spigotmc.org/resources/1-8-1-17-%E2%9C%85-advancedspawners-%E2%9C%85-11x-custom-mobs-%E2%AD%95-create-custom-mobs-in-game-%E2%9A%A1-25-sale-%E2%9A%A1.75458/
