### ISSUE TITLE
[Issue] Spamming console

### ISSUE THREAD

**Issue by LeCraft2Ouf** [GC-spigot/AdvancedSpawners#317]
Version plugin : 3.5.6
Minecraft version : 1.8.8

Hello, since I put the last version of your plugin, I have this error that comes very often in my console:

[00:32:41 ERROR]: Could not pass event EntityDamageEvent to AdvancedSpawners v3.5.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-TacoSpigot-"95870a93"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [server.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [server.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [server.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:539) [server.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:604) [server.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:590) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.EntityItem.damageEntity(EntityItem.java:244) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.Entity.burn(Entity.java:897) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:777) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.EntityItem.t_(EntityItem.java:82) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1651) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1618) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1455) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:848) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [server.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [server.jar:git-TacoSpigot-"95870a93"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoSuchFieldError: HOT_FLOOR
        at gcspawners.EntityDamageHandler.onDamageNoPlayer(EntityDamageHandler.java:221) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-TacoSpigot-"95870a93"]
        ... 22 more

**Comment by GC-spigot** [comment]
Fixed
