### ISSUE TITLE
[Issue] AdvancedSpawners not enabled

### ISSUE THREAD

**Issue by Rismack** [GC-spigot/AdvancedSpawners#321]
**Describe the bug**
Hello! I bought AdvancedSpawners a few hours ago but after putting it in the plugins folder and restarting the server, the plugin is not enabled and the following error appears in the console:

**Screenshots / Video**
[01:06:29 INFO]: [AdvancedSpawners] Enabling AdvancedSpawners v3.5.9
[01:06:29 INFO]: [AdvancedSpawners] Loaded 36,570 custom heads
[01:06:29 INFO]: [AdvancedSpawners] Loaded 10 mob configurations.
[01:06:29 ERROR]: Error occurred while enabling AdvancedSpawners v3.5.9 (Is it up to date?)
gcspawners.NbtApiException: Exception while getting an Itemstack's NBTCompound!
        at gcspawners.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:112) ~[?:?]
        at gcspawners.NBTItem.getCompound(NBTItem.java:18) ~[?:?]
        at gcspawners.NBTReflectionUtil.setData(NBTReflectionUtil.java:542) ~[?:?]
        at gcspawners.NBTCompound.setString(NBTCompound.java:36) ~[?:?]
        at gcspawners.NBTapi.addNBTTag(NBTapi.java:15) ~[?:?]
        at gcspawners.ShopInventoryHandler.load(ShopInventoryHandler.java:67) ~[?:?]
        at gcspawners.Core.reload(Core.java:324) ~[?:?]
        at gcspawners.Core.onEnable(Core.java:111) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: gcspawners.NbtApiException: Method not loaded! 'NMSITEM_GETTAG'
        at gcspawners.ReflectionMethod.run(ReflectionMethod.java:208) ~[?:?]
        at gcspawners.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:109) ~[?:?]
        ... 17 more
[01:06:29 INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v3.5.9
[01:06:29 ERROR]: Error occurred while disabling AdvancedSpawners v3.5.9 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "gcspawners.AdvancedSpawnerHandler.save(boolean)" because "gcspawners.Core.spawnersHandler" is null
        at gcspawners.Core.onDisable(Core.java:494) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Server Information:**
- Minecraft Version: 1.16.5 (git-Paper-788)
- Plugin Version: 3.5.9

**Comment by GC-spigot** [comment]
Fixed
