### ISSUE TITLE
console WARN SPAM

### ISSUE THREAD

**Issue by el211** [GC-spigot/AdvancedSpawners#323]
[14:24:48 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.ArmorStand.teleport(org.bukkit.Location)" because the return value of "gcspawners.ArmorStandLocation.getArmorStand()" is null
[14:24:48 WARN]:        at AdvancedSpawners-3.6.0.jar//gcspawners.CustomEntityInstance.move(CustomEntityInstance.java:90)
[14:24:48 WARN]:        at AdvancedSpawners-3.6.0.jar//gcspawners.CustomEntityHandler.move(CustomEntityHandler.java:189)
[14:24:48 WARN]:        at AdvancedSpawners-3.6.0.jar//gcspawners.CustomEntityHandler.access$100(CustomEntityHandler.java:28)
[14:24:48 WARN]:        at AdvancedSpawners-3.6.0.jar//gcspawners.CustomEntityHandler$1.run(CustomEntityHandler$1.java:131)
[14:24:48 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:24:48 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:24:48 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1591)
[14:24:48 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:528)
[14:24:48 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1507)
[14:24:48 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1300)
[14:24:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[14:24:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by GC-spigot** [comment]
should be fixed

**Comment by el211** [comment]
how? there is not update for advanced spawners

**Comment by GC-spigot** [comment]
I'm replying as I fix issues, not as I post the update lol. Just wait a little for next update.

**Comment by el211** [comment]
oh alright i thought it was fixed i went to see the update couldnt find it xD
sure np
