### ISSUE TITLE
ERROR AND MY SERVER CRASH CAUSE OF THT [Issue]

### ISSUE THREAD

**Issue by rareskiing** [GC-spigot/AdvancedSpawners#371]
**Describe the bug**
[13:29:31] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedSpawners v3.8.0
java.lang.NullPointerException: Cannot invoke "gcspawners.CustomEntityInstance.getEntityMeta()" because "<local3>" is null
	at gcspawners.EntityDamageHandler.handleCustomDamage(EntityDamageHandler.java:208) ~[AdvancedSpawners-3.8.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor463.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1152) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1011) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:963) ~[paper-1.19.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1186) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2097) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1074) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1369) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:981) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1042) ~[?:?]
	at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1605) ~[?:?]
	at net.minecraft.world.entity.monster.Phantom$PhantomSweepAttackGoal.tick(Phantom.java:463) ~[?:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:151) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:142) ~[?:?]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:867) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3307) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:634) ~[?:?]
	at net.minecraft.world.entity.monster.Phantom.aiStep(Phantom.java:151) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2949) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
	at net.minecraft.world.entity.monster.Phantom.tick(Phantom.java:125) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1155) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
**To Reproduce**
When somone attack a mob and another error when getting attacked

**Screenshots / Video**
No video or screen needed

**Server Information (please complete the following information):**
 - SpigotPaper 1.19
- 3.8.0 last

**Comment by maxedrom** [comment]
the same to me, i opened a ticket, no body spoke me.
