### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by austinprado** [GC-spigot/AdvancedSpawners#85]
Whenever a large group stack of dragons is hit it lags the server hard. It also seems to be the cause of mem crashes. 
I can provide video proof if necessary
2:51:17] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world entities
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:931) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperspigot.jar:git-Paper-"5d8b3d49"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
	at org.spigotmc.ActivationRange.activateChunkEntities(ActivationRange.java:153) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:134) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1538) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:920) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	... 4 more
[02:51:17] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at org.spigotmc.ActivationRange.activateChunkEntities(ActivationRange.java:153) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:134) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1538) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:920) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[paperspigot.jar:git-Paper-"5d8b3d49"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperspigot.jar:git-Paper-"5d8b3d49"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by GC-spigot** [comment]
Yes would be great to see a video so I could better understand the problem.
