### ISSUE TITLE
[Issue]Block Place Event 

### ISSUE THREAD

**Issue by megamineservidores** [GC-spigot/AdvancedSpawners#94]
[03:24:51 ERROR]: Could not pass event BlockPlaceEvent to AdvancedSpawners v2.2.1
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/IChatBaseComponent
        at gc.spawners.handlers.customSpawners.listeners.SpawnerPlaceEvent.onPlace(SpawnerPlaceEvent.java:41) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor492.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-342]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:346) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:237) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:514) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1413) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1104) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1058) ~[patched_1.15.2.jar:git-Paper-342]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:973) ~[patched_1.15.2.jar:git-Paper-342]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.IChatBaseComponent
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.15.2.jar:git-Paper-342]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-342]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
        ... 23 more

Minecraft Server - 1.15.2
- Plugin Version 2.2.1

**Comment by GC-spigot** [comment]
Fixed
