### ISSUE TITLE
[Issue] BUG MULTIPLE

### ISSUE THREAD

**Issue by LeCraft2Ouf** [GC-spigot/AdvancedSpawners#95]
Hello, thank you for your recent updates.

But after testing, I see that there are still some bugs. I quoted it to you:
BUG:
1 - The spawner stack limit is still not working. (SpawnerStackLimit: 3 but I can put more than 3)

2 - After modifying the configuration upgrades.purchased, the modifications do not apply to the new configuration.

3 - Material spawners, do not work.

`[16:21:32] [Server thread/WARN]: java.lang.IllegalArgumentException: Material cannot be null
[16:21:32] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[16:21:32] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85)
[16:21:32] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73)
[16:21:32] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61)
[16:21:32] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:47)
[16:21:32] [Server thread/WARN]: 	at gcspawners.SpawnerData$1.run(SpawnerData$1.java:59)
[16:21:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[16:21:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[16:21:32] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[16:21:32] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[16:21:32] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[16:21:32] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[16:21:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:21:32] [Server thread/WARN]: Exception loading entity: 
net.minecraft.server.v1_15_R1.ReportedException: Loading entity NBT
	at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1857) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.EntityTypes.lambda$a$1(EntityTypes.java:305) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.SystemUtils.a(SystemUtils.java:233) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:302) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.EntityTypes.b(EntityTypes.java:346) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.EntityTypes.a(EntityTypes.java:327) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MobSpawnerAbstract.c(MobSpawnerAbstract.java:130) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.TileEntityMobSpawner.tick(SourceFile:62) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.World.tickBlockEntities(World.java:798) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:570) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-354]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.EntityItem.setItemStack(EntityItem.java:433) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.EntityItem.a(EntityItem.java:316) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.Entity.f(Entity.java:1770) ~[patched_1.15.2.jar:git-Paper-354]
	... 14 more
[16:21:37] [Server thread/WARN]: java.lang.IllegalArgumentException: Material cannot be null
[16:21:37] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[16:21:37] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85)
[16:21:37] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73)
[16:21:37] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61)
[16:21:37] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:47)
[16:21:37] [Server thread/WARN]: 	at gcspawners.SpawnerData$1.run(SpawnerData$1.java:59)
[16:21:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[16:21:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[16:21:37] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[16:21:37] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[16:21:37] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[16:21:37] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[16:21:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

Thank you for your work.
Cordially

**Server Information (please complete the following information):**
 - Minecraft Version Paper 1.15.2
- Plugin Version LATEST

**Comment by GC-spigot** [comment]
1st - Fixed
2nd - It was an issue with reloading and not updating some messages but the actual message would change after server reload / restart, however it's now fixed.
3rd - What material are you using? Server is reporting that the material set for spawner is invalid

**Comment by LeCraft2Ouf** [comment]
Bonjour, merci.

Je peut faire avec n'importe quelle ressource, tous ne fonctionnent pas
